#app_admin:
#    resource: "@AppAdminBundle/Resources/config/routing.xml"
#    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.xml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin